# UNPIVOT

In [1]:
import pandas as pd
Path=r'C:\Users\sanab\Desktop\pandas\Superstore.xlsx'
Path
orders=pd.read_excel(Path)
orders
df=pd.pivot_table(orders,index='Region',columns='Category',values='Sales',aggfunc='sum').reset_index()
df

Category   Region    Furniture  Office Supplies  Technology
0         Central  163797.1638       167026.415  170416.312
1            East  208291.2040       205516.055  264973.981
2           South  117298.6840       125651.313  148771.908
3            West  252612.7435       220853.249  251991.832

In [2]:
pd.melt(df,id_vars='Region').rename(columns={'value':'Sales'})

     Region         Category        Sales
0   Central        Furniture  163797.1638
1      East        Furniture  208291.2040
2     South        Furniture  117298.6840
3      West        Furniture  252612.7435
4   Central  Office Supplies  167026.4150
5      East  Office Supplies  205516.0550
6     South  Office Supplies  125651.3130
7      West  Office Supplies  220853.2490
8   Central       Technology  170416.3120
9      East       Technology  264973.9810
10    South       Technology  148771.9080
11     West       Technology  251991.8320

DUPLICATE

In [3]:
df =  pd.DataFrame({'order_id':[1,2,2,3,4],'amount':[100,100,100,200,300]})

In [5]:
orders

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,Dispatch Time,Unnamed: 22,Descrete,quantity,dispatch time
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2,NaN,NaN,NaN,NaN
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2,NaN,NaN,NaN,NaN
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,3,NaN,NaN,NaN,NaN
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,6,NaN,NaN,NaN,NaN
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,6,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,1,NaN,NaN,NaN,NaN
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,4,NaN,NaN,NaN,NaN
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,4,NaN,NaN,NaN,NaN
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,4,NaN,NaN,NaN,NaN
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,5,NaN,NaN,NaN,NaN

In [4]:
df[df.duplicated(keep='first')]

   order_id  amount
2         2     100

In [6]:
df.drop_duplicates(inplace=True) # inplace is for permanent changes

In [7]:
df

   order_id  amount
0         1     100
1         2     100
3         3     200
4         4     300

MISSING VALUE

In [13]:
import numpy as np
import pandas as pd

In [15]:
df=pd.DataFrame({"Data":['1','2','3','4','5','6','7','8'],"Sales" : [2133,np.nan,334,3232,np.nan,3234,3434,4343]})

In [16]:
df

  Data   Sales
0    1  2133.0
1    2     NaN
2    3   334.0
3    4  3232.0
4    5     NaN
5    6  3234.0
6    7  3434.0
7    8  4343.0

In [ ]:
df.fillna(55)  #fill missing value

  Data   Sales
0    1  2133.0
1    2    55.0
2    3   334.0
3    4  3232.0
4    5    55.0
5    6  3234.0
6    7  3434.0
7    8  4343.0

In [18]:
df.bfill()   #fill previous record when missing value comes

  Data   Sales
0    1  2133.0
1    2   334.0
2    3   334.0
3    4  3232.0
4    5  3234.0
5    6  3234.0
6    7  3434.0
7    8  4343.0

In [19]:
df.ffill()  #fill upcoming value with nan

  Data   Sales
0    1  2133.0
1    2  2133.0
2    3   334.0
3    4  3232.0
4    5  3232.0
5    6  3234.0
6    7  3434.0
7    8  4343.0